### ISSUE TITLE
terra

### ISSUE THREAD

**Issue by glycerine** [titan-lang/titan-v0#111]
Not trying to troll you, but you have heard of terra, right? It's statically typed, highly performance, same syntax as lua plus types, and uses lua as its metalanguage. It compiles using the llvm framework. It's already done. http://terralang.org/

It's great fun to work on new languages, but if you could describe in your README why and how you are taking a different approach, versus terra for example, that would be useful.

Thanks. And good luck!

**Comment by hishamhm** [comment]
Hi! Being programming language researchers, we are of course aware of Terra, it's an excellent project!

In terms of language, Terra is a low-level systems language (think replacing C/C++) designed for multi-stage programming, using Lua 5.1 as a metalanguage for staged code generation (think Lua as a replacement for C++ template metaprogramming). Titan is an application language (think at the level of Go/C#), using Lua 5.3 as a scripting language (not for scripting the compiler, but for writing scriptable applications in Titan + Lua instead of C + Lua).

In terms of implementation, Terra leverages the LuaJIT FFI and LLVM. Titan integrates with the standard Lua 5.3 interpreter and generates C code.

The two languages are aimed at solving different problems, and do so taking different approaches. So we believe there is room for both!

**Comment by glycerine** [comment]
@hishamhm Very nice. Thank you.

**Comment by flamendless** [comment]
Im just curious about the effect/usage of titan (that uses lua 5.3) if im going to use this with the love game framework (that uses lua 5.1)

**Comment by hugomg** [comment]
As far as I know, LÖVE uses LuaJIT instead of PUC-Lua.  LuaJIT compatibility is currently not on our short-term roadmap.
